services:
  frontend:
    build: frontend
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=PRODUCTION
  api:
    build: api
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=PRODUCTION
